name: ci
on: pull_request
jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      URL: ${{ secrets.URL }}
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Build baton-zuper
        run: go build -o baton-zuper ./cmd/baton-zuper
      - name: Validate capabilities
        run: |
          ./baton-zuper \
            --api-url "$URL" \
            --api-key "$TOKEN" \
          capabilities
      - name: Run basic sync test
        run: |
          ./baton-zuper \
            --api-url "$URL" \
            --api-key "$TOKEN" \
            --log-level debug \
            --file sync.c1z

          if [ ! -f "sync.c1z" ]; then
            echo "Error: File sync.c1z was not generated."
            exit 1
          fi
      - name: List Baton Commands
        run: ./baton-zuper --help
